// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.924
package components

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func PostCard(post Post) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<div class=\"retro-card relative flex flex-col group cursor-pointer\" hx-get=\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var2 string
		templ_7745c5c3_Var2, templ_7745c5c3_Err = templ.JoinStringErrs(post.Link)
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `views/components/postCard.templ`, Line: 4, Col: 87}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var2))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "\" hx-push-url=\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var3 string
		templ_7745c5c3_Var3, templ_7745c5c3_Err = templ.JoinStringErrs(post.Link)
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `views/components/postCard.templ`, Line: 4, Col: 113}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var3))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, "\" hx-target=\"#content\" hx-swap=\"innerHTML\"><div class=\"absolute -top-3 -right-3 bg-retro-pink border-2 border-retro-black px-3 py-1 rounded-full font-heading font-bold text-xs shadow-[2px_2px_0px_#000] rotate-12 z-20\">#Log</div><div class=\"bg-gray-100 border-2 border-retro-black rounded-lg shadow-hard h-full flex flex-col p-4 pb-12 relative overflow-hidden\"><div class=\"absolute top-0 left-0 w-full h-4 border-b-2 border-retro-black flex gap-1 justify-center items-center bg-gray-300\"><div class=\"w-[2px] h-full bg-retro-black\"></div><div class=\"w-[2px] h-full bg-retro-black\"></div><div class=\"w-[2px] h-full bg-retro-black\"></div></div><div class=\"mt-6 bg-white border-2 border-retro-black rounded-md p-4 flex-1 flex flex-col gap-3 relative z-10 group-hover:bg-retro-yellow/20 transition-colors\"><div class=\"w-full h-32 bg-retro-black rounded overflow-hidden border-2 border-retro-black mb-2\"><img alt=\"Cover\" class=\"w-full h-full object-cover opacity-80 hover:opacity-100 transition-opacity\" src=\"https://lh3.googleusercontent.com/aida-public/AB6AXuBsXa0NBoZl3hnGdPpvN3t-QweuCNSfskjQ2TWRmDU8V4kj9ivA_o5KmD-YBAthv6ybmWGmPUVndVI44xKF8ZgFVXHCm1raVGePEe8HD-pcAjqogBLpUvQSFp5NZsRHZfb5kBVZ8R_521jCfpI1-VWTXVk5mATHBE2SGl6ZgjastFni16iB9nPI5jZw79HNZEmeKdPDBEYUAJJiO4YcQis2xn2K5MP3Z9tH5yrX5gAoxTgrrgYAvHGRAy6dFNgwz5yYYlrDpPi7tAvR\"></div><h3 class=\"font-heading font-bold text-xl leading-tight uppercase line-clamp-2\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var4 string
		templ_7745c5c3_Var4, templ_7745c5c3_Err = templ.JoinStringErrs(post.Title)
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `views/components/postCard.templ`, Line: 16, Col: 96}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var4))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 4, "</h3><p class=\"text-xs font-body leading-tight line-clamp-3 text-gray-600\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var5 string
		templ_7745c5c3_Var5, templ_7745c5c3_Err = templ.JoinStringErrs(post.Content)
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `views/components/postCard.templ`, Line: 17, Col: 88}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var5))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 5, "</p><div class=\"mt-auto pt-2 flex justify-between items-center\"><span class=\"font-pixel text-xs text-gray-500\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var6 string
		templ_7745c5c3_Var6, templ_7745c5c3_Err = templ.JoinStringErrs(post.Date)
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `views/components/postCard.templ`, Line: 19, Col: 63}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var6))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 6, "</span> <span class=\"material-symbols-outlined text-lg group-hover:translate-x-1 transition-transform\">arrow_forward</span></div></div><div class=\"absolute bottom-0 left-1/2 -translate-x-1/2 w-3/4 h-6 border-t-2 border-x-2 border-retro-black bg-gray-300 rounded-t flex justify-center items-center gap-2\"><div class=\"w-1 h-3 bg-retro-black/20 rounded-full\"></div><div class=\"w-1 h-3 bg-retro-black/20 rounded-full\"></div><div class=\"w-1 h-3 bg-retro-black/20 rounded-full\"></div></div></div></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
